_extends: .github

repository:
  name: base
  description: Base repository with default settings and configs
  homepage: https://github.com/premiscale/base

  # A comma-separated list of topics to set on the repository
  topics: settings
  private: true
