repository:
  name: .github
  description: Base .github/settings.yml for repositories to reference
  homepage: https://github.com/premiscale/.github
  topics: github
  private: true
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false

labels:
  - name: bug
    color: CC0000
    description: An issue with the system 🐛.

  - name: feature
    color: "#336699"
    description: New functionality.

  - name: Help Wanted
    new_name: first-timers-only

milestones: []
collaborators: []
teams: []

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []
