repository:
  # The name of the repository. Changing this will rename the repository
  name: .github

  # A short description of the repository that will show up on GitHub
  description: description of repo

  # A URL with more information about the repository
  homepage: https://github.com/premiscale/.github

  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699

# Collaborators: give specific users access to this repository.
collaborators:
  #- username: bkeepers
  #  # Note: Only valid on organization-owned repositories.
  #  # The permission to grant the collaborator. Can be one of:
  #  # * `pull` - can pull, but not push to or administer this repository.
  #  # * `push` - can pull and push, but not administer this repository.
  #  # * `admin` - can pull, push and administer this repository.
  #  permission: push

  - username: hubot
    permission: pull
  - username:
    permission: pull
