version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.9.1
  general: bjd2385/general@0.7.7


workflows:
  base:
    jobs:
      - dynamic/continue:
          context: circleci
          modules: |
            /scripts

      - general/github-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
